name: RushlandAPI
authors: [Aquazus, Zaral]
main: fr.aquazus.rushland.api.BukkitInjector
version: ${project.version}
commands:
   grade:
      description: Commande de grade
      aliases: [rank]
   spec:
      description: Passer en mode spectateur
      aliases: [spectator, spectateur]
   tp:
      description: Commande de teleportation
   aacautoreport:
      description: Commande de report RAT
   leave:
      description: Quitter la partie
   rlshop:
      description: Commande technique
   addshopcoins:
      description: Ajouter des ShopCoins
   addrushcoins:
      description: Ajouter des RushCoins